// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/SwissMusicCoworkingLandingPage-IsqrAi/App.tsx": () => import("../components/mockups/templates/SwissMusicCoworkingLandingPage-IsqrAi/App.tsx"),
  "./components/mockups/templates/CloudSpendActivityCalendar-F5Puvt/App.tsx": () => import("../components/mockups/templates/CloudSpendActivityCalendar-F5Puvt/App.tsx")
};
